export const CONFIG = {
  // === Renderer ===
  RENDERER_PIXEL_RATIO_MAX: 2,
  RENDERER_ANTIALIAS: true,

  // === Camera ===
  CAMERA_FOV: 75,
  CAMERA_NEAR: 0.1,
  CAMERA_FAR: 2000,

  // === State Machine ===
  STATE_TRANSITION_COOLDOWN_MS: 300,

  // === Descent ===
  DESCENT_DURATION_SECONDS: 14,
  DESCENT_START_Y: 300,
  DESCENT_END_Y: -190,
  DESCENT_MAX_DELTA_SECONDS: 0.1,

  // === Terrain ===
  TERRAIN_SIZE: 400,
  TERRAIN_SEGMENTS: 120,
  TERRAIN_Y_OFFSET: -200,
  TERRAIN_FLAT_RADIUS: 30,

  // === Starfield ===
  STAR_COUNT: 4000,
  STAR_SPREAD: 500,
  STAR_DEPTH: 1000,

  // === Structures ===
  STRUCTURE_MIN_RADIUS: 20,
  STRUCTURE_MAX_RADIUS: 60,
  STRUCTURE_BASE_SCALE: 0.5,
  STRUCTURE_PRIORITY_SCALE_FACTOR: 0.15,

  // === Free Camera ===
  FREE_CAM_MOVE_SPEED: 15,
  FREE_CAM_LOOK_SENSITIVITY: 0.002,
  FREE_CAM_BLINK_DURATION_MS: 300,
  FREE_CAM_BLINK_MAX_DISTANCE: 40,
  FREE_CAM_TERRAIN_BOUNDARY_RADIUS: 180,
  FREE_CAM_HEIGHT_ABOVE_TERRAIN: 5,
  FREE_CAM_PITCH_MIN: -Math.PI / 3,
  FREE_CAM_PITCH_MAX: Math.PI / 3,

  // === Fixed Camera ===
  FIXED_CAM_ORBIT_RADIUS: 50,
  FIXED_CAM_ORBIT_SPEED: 0.08,
  FIXED_CAM_HEIGHT: -175,
  FIXED_CAM_PARALLAX_STRENGTH: 8,

  // === Particles ===
  AMBIENT_DUST_COUNT: 600,
  AMBIENT_DUST_SPREAD: 100,
  STRUCTURE_PARTICLE_COUNT: 30,

  // === Effects ===
  BLOOM_STRENGTH: 1.5,
  BLOOM_RADIUS: 0.4,
  BLOOM_THRESHOLD: 0.6,

  // === HUD ===
  HUD_FADE_IN_DURATION_MS: 500,
  HUD_FADE_OUT_DURATION_MS: 300,

  // === Colors (neon palette) ===
  NEON_COLORS: [0xff00cc, 0x00ffc8, 0xff6600, 0x00aaff, 0xffdd00, 0xff0066, 0x88ff00] as const,
  SKY_COLOR: 0x020010,
  TERRAIN_BASE_COLOR: 0x0a0a1a,
  TERRAIN_WIRE_COLOR: 0x00ff88,
  TERRAIN_WIRE_OPACITY: 0.06,
  FOG_COLOR: 0x020010,
  FOG_DENSITY: 0.008,

  // === Mobile ===
  MOBILE_BREAKPOINT_PX: 768,

} as const;
