export const CONFIG = {
  // === Renderer ===
  RENDERER_PIXEL_RATIO_MAX: 2,
  RENDERER_ANTIALIAS: true,

  // === Camera ===
  CAMERA_FOV: 75,
  CAMERA_NEAR: 0.1,
  CAMERA_FAR: 2000,

  // === State Machine ===
  STATE_TRANSITION_COOLDOWN_MS: 300,

  // === Descent ===
  DESCENT_DURATION_SECONDS: 14,
  DESCENT_START_Y: 300,
  DESCENT_END_Y: -190,
  DESCENT_MAX_DELTA_SECONDS: 0.1,

  // === Terrain ===
  TERRAIN_SIZE: 400,
  TERRAIN_SEGMENTS: 120,
  TERRAIN_Y_OFFSET: -200,
  TERRAIN_FLAT_RADIUS: 30,

  // === Starfield ===
  STAR_COUNT: 4000,
  STAR_SPREAD: 500,
  STAR_DEPTH: 1000,

  // === Structures ===
  STRUCTURE_MIN_RADIUS: 20,
  STRUCTURE_MAX_RADIUS: 60,
  STRUCTURE_BASE_SCALE: 0.5,
  STRUCTURE_PRIORITY_SCALE_FACTOR: 0.15,

  // === Free Camera ===
  FREE_CAM_MOVE_SPEED: 15,
  FREE_CAM_LOOK_SENSITIVITY: 0.006,
  FREE_CAM_ARROW_LOOK_SPEED: 2.0,
  FREE_CAM_BLINK_DURATION_MS: 300,
  FREE_CAM_BLINK_MAX_DISTANCE: 30,
  FREE_CAM_TERRAIN_BOUNDARY_RADIUS: 180,
  FREE_CAM_HEIGHT_ABOVE_TERRAIN: 5,
  FREE_CAM_PITCH_MIN: -Math.PI / 3,
  FREE_CAM_PITCH_MAX: Math.PI / 3,
  FREE_CAM_BLINK_STREAK_DURATION_MS: 750,
  FREE_CAM_BLINK_STREAK_LINE_COUNT: 50,

  // === Fixed Camera ===
  FIXED_CAM_ORBIT_RADIUS: 50,
  FIXED_CAM_ORBIT_RADIUS_MIN: 5,
  FIXED_CAM_ORBIT_RADIUS_MAX: 300,
  FIXED_CAM_ORBIT_SPEED: 0.08,
  FIXED_CAM_HEIGHT: -175,
  FIXED_CAM_PARALLAX_STRENGTH: 8,
  FIXED_CAM_DRAG_SENSITIVITY: 0.004,
  FIXED_CAM_PINCH_SENSITIVITY: 0.04,
  FIXED_CAM_RESUME_ORBIT_DELAY: 2000,
  FIXED_CAM_BLINK_DURATION: 300,
  FIXED_CAM_DOUBLE_TAP_MAX_MS: 300,
  FIXED_CAM_DOUBLE_TAP_MAX_PX: 20,
  FIXED_CAM_PITCH_MIN: -1.0,
  FIXED_CAM_PITCH_MAX: 0.8,
  FIXED_CAM_SCROLL_SENSITIVITY: 4.0,
  FIXED_CAM_DESKTOP_DEFAULT_RADIUS: 140,
  FIXED_CAM_DESKTOP_DEFAULT_PITCH: 0.55,
  FIXED_CAM_ZOOM_PITCH_CLOSE: -0.2,
  FIXED_CAM_ZOOM_PITCH_FAR: 0.7,

  // === Particles ===
  AMBIENT_DUST_COUNT: 1200,
  AMBIENT_DUST_SPREAD: 120,
  STRUCTURE_PARTICLE_COUNT: 30,

  // === Effects ===
  BLOOM_STRENGTH: 2.0,
  BLOOM_RADIUS: 0.5,
  BLOOM_THRESHOLD: 0.45,

  // === HUD ===
  HUD_FADE_IN_DURATION_MS: 500,
  HUD_FADE_OUT_DURATION_MS: 300,
  HELP_HINT_AUTO_DISMISS_MS: 7000,

  // === Colors (neon palette) ===
  NEON_COLORS: [0xff00cc, 0x00ffc8, 0xff6600, 0x00aaff, 0xffdd00, 0xff0066, 0x88ff00] as const,
  SKY_COLOR: 0x020010,
  TERRAIN_BASE_COLOR: 0x0a0a1a,
  TERRAIN_WIRE_COLOR: 0x00ff88,
  TERRAIN_WIRE_OPACITY: 0.08,
  FOG_COLOR: 0x020010,
  FOG_DENSITY: 0.007,

  // === Mobile ===
  MOBILE_BREAKPOINT_PX: 768,

} as const;
